### ISSUE TITLE
No Chinese in my dirs and files

### ISSUE THREAD

**Issue by twocucao** [coursera-dl/coursera#326] opened 2015-03-28 00:32 UTC
When I run it in win8.1(Python3) ,It just rename the Chinese videos srts pdfs the name without chinese.
But if its a course in english,,that will be fine

**Comment by rbrito** [comment] 2015-03-29 18:04
Hi, @twocucao.

On Mar 27 2015, twocucao wrote:
> When I run it in win8.1(Python3) ,It just rename the Chinese videos srts
> pdfs the name without chinese.
> But if its a course in english,,that will be fine

Yes, that's the expected behavior. Can you please try running coursera-dl
with the option `--unrestricted-filenames`?

It may not work due to failures trying to write non-ascii filenames on
windows, but I would love to know your experience.


Hope this helps,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by twocucao** [comment] 2015-03-29 23:03
oh,That works ,Thankyou ~~

**Comment by rbrito** [comment] 2015-03-30 02:28
Thanks for the feedback. I'm closing this now, then.

**Closed by rbrito** 2015-03-30 02:28 UTC
