### ISSUE TITLE
On windows path+file name greater than 255 download failed,bug fixed here is the way

### ISSUE THREAD

**Issue by sunsocool** [coursera-dl/coursera#239] opened 2014-03-14 13:28 UTC
when I download https://class.coursera.org/artificialvision-001  course 1.7 "
1.7 Examples of Discrete High-level vision (multi-object tracking with occlusion reasoning, 3D pose estimation from 2D images, image parsing using shape grammars towards large scale modeling and reconstruction) (13:45)"
    Always failed as I check the error log I found that the parse html and generate file path is correct but the log indicated that file not found. As I download the course manually with chrome,I found that I can't copy the file to other place OS alert file name too long.
    So I dig into the code  and fixed the bug, the idea is if path + file name greater than 210 characters (take smaller for sure)  then take the former 210 character + file format.
   here the code:
in file coursera-dl.py about line 309, in function def download_lectures(downloader,...
    after line 379 procedure :
            # write lecture resources
            for fmt, url, title in resources_to_get:
                if combined_section_lectures_nums:
                    lecfn = os.path.join(
                        sec,
                        format_combine_number_resource(
                            secnum + 1, lecnum + 1, lecname, title, fmt))
                else:
                    lecfn = os.path.join(
                        sec, format_resource(lecnum + 1, lecname, title, fmt))   
                        
attach the code modifyed by me:

  #  check if path length exceed OS defined length
                if len(lecfn)>210:
                    print("&&&&&&&&&&&&&&&&&&&&&&")
                    print("Named Modifyed: ",lecfn)
                    lecfn=lecfn[:210]+"__."+fmt
                    print("New Name: ",lecfn)
                    print("&&&&&&&&&&&&&&&&&&&&&&")
  #  modifyed by sunsocool @ 2014/3/14  

Then you'll done,Good luck!

**Comment by rbrito** [comment] 2015-04-24 05:34
Hi, people.

As far as I can see, this issue is a duplicate of Just as a duplicate of issue #217. Let us just consolidate our discussions (and proposed solutions) there, so that I can better concentrate on the issue at hand.

I am, therefore, closing this bug.


Regards, Rogério Brito.

**Closed by rbrito** 2015-04-24 05:34 UTC
Labels: duplicate, enhancement
