### ISSUE TITLE
Downloading https://www.coursera.org/learn/... classes

### ISSUE THREAD

**Issue by HostClubKea** [coursera-dl/coursera#333] opened 2015-04-09 20:18 UTC
Are there are any way to download classes https://www.coursera.org/learn/... ?

For example https://www.coursera.org/learn/childnutrition/outline

**Comment by rbrito** [comment] 2015-04-09 23:14
Hi.

On Apr 09 2015, HostClubKea wrote:
> Are there are any way to download classes https://www.coursera.org/learn/... ?
> 
> For example https://www.coursera.org/learn/childnutrition/outline

Sure, just get the latest version of our tree and use the `--on-demand`
command line option.


Hope this helps,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by Ryan147** [comment] 2015-04-11 14:43
I tried using the --on-demand option but it is not working. 

Used the upgrade option but it says requirement is already up-to-date:
"C:\Python27\scripts\pip.exe" install --upgrade coursera-dl
Requirement already up-to-date: coursera-dl in c:\python27\lib\site-packages
Requirement already up-to-date: beautifulsoup4 in c:\python27\lib\site-packages (from coursera-dl)
Requirement already up-to-date: mechanize in c:\python27\lib\site-packages (from coursera-dl)
Requirement already up-to-date: argparse in c:\python27\lib\site-packages (from coursera-dl)
Cleaning up...

Coursera-dl-script.py: error: unrecognized arguments: --on-demand

C:\Python27>"C:\Python27\python.exe" "c:\Temp\listPackage.py"
                    udacity-dl     1.1.4   up to date
                      argparse     1.3.0   up to date
                beautifulsoup4     4.3.2   up to date
                   coursera-dl     3.1.1   up to date
                     mechanize     0.2.5   up to date
                     pyDatalog    0.15.2   up to date
                      requests     2.6.0   up to date
                           six     1.9.0   up to date
                    virtualenv    12.1.1   up to date
                   youtube-dl 2015.04.09   no releases at pypi

**Comment by rbrito** [comment] 2015-04-14 02:19
Hi, @Ryan147.

You are using another project called `coursera-dl`. We still do not release our project via PyPi. Yes, we know that this is confusing, but you are welcome to try our version (I suspect that you will have to uninstall the pip package coursera-dl, to avoid confusion).

Then, getting a fresh copy of our project either via git or via https://github.com/coursera-dl/coursera/archive/master.zip will give you working support to download courses with the `--on-demand` option.

Hope this helps,

Rogério Brito.

**Comment by marcofat** [comment] 2015-04-22 18:37
Hi Rogério, 
I downloaded a copy of your software (thank you!) from https://github.com/coursera-dl/coursera/archive/master.zip and used it on a Python brandnew installation. After installing the dependencies included in requirements.txt I then tried to download educational materials of a couple of courses:
https://www.coursera.org/learn/competitivestrategy/outline
https://www.coursera.org/learn/advanced-competitive-strategy

In order to download them I used the following commands:
coursera-dl -u xxx -p yyy --on-demand learn/competitivestrategy 
coursera-dl -u xxx -p yyy --on-demand learn/advanced-competitive-strategy 

...but I got the following aswers:
Downloading class: learn/competitivestrategy
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Error 404 Client Error: Not Found getting page https://www.coursera.org/api/open
course.v1/course/learn/competitivestrategy
HTTPError 404 Client Error: Not Found

Downloading class: learn/advanced-competitive-strategy
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Error 404 Client Error: Not Found getting page https://www.coursera.org/api/open
course.v1/course/learn/advanced-competitive-strategy
HTTPError 404 Client Error: Not Found

Is there something you can recomend me to do in order to overcome the HTTPError?
Thank you and have a good day!
Marco

**Comment by rbrito** [comment] 2015-04-23 07:03
Hi.

On Apr 22 2015, marcofat wrote:
> I downloaded a copy of your software (thank you!) from
> https://github.com/coursera-dl/coursera/archive/master.zip and used it on
> a Python brandnew installation.

You're welcome. :)

> coursera-dl -u xxx -p yyy --on-demand learn/competitivestrategy 
> coursera-dl -u xxx -p yyy --on-demand learn/advanced-competitive-strategy 
(...)
> Is there something you can recomend me to do in order to overcome the
> HTTPError?

Yes. Try removing the "learn/" prefix from the courses names. Use just
"competitivestrategy", for instance.


Let me know if that works for you.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by rbrito** [comment] 2015-04-23 07:06
As this was more of a question and this has already been answered, I am closing this bug. If some other problems appear, please consider opening a different issue with detailed information on the problems.

**Closed by rbrito** 2015-04-23 07:06 UTC
Labels: question

**Comment by Ryan147** [comment] 2015-04-23 07:44
Hello Rogerio,

Thank you for answering my question and that there is another coursera-dl package.

I downloaded your package and used it on an on-demand course. Is there an argument I have to give to enable downloading subtitles as well?

**Comment by rbrito** [comment] 2015-04-24 03:21
@Ryan147, it should have downloaded all the subtitles automatically. If it doesn't (and the subtitles *are* present), would you please open another issue separate from this so that it doesn't get lost?

It would also be helpful if you provided some context, so that those of us with little memory (my case!) can remember what the issue is. :)

**Comment by facetofacestudy** [comment] 2015-12-24 07:03
Yes i am also some disappoint with the coursera so i have start taking classes with www.facetofacestudy.com

**Comment by kartiknifm** [comment] 2017-09-04 10:17
I study your blog and discover it quite appealing and useful. Moreover, I would propose you to keep on updating and posting such relevant articles from time to time. Keep doing the good work.
<a href="http://www.onlinenifm.com/">online course stock market</a>
